version: '3.8'

services:
  database:
    image: 'bitnami/postgresql'
    container_name: container_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_ENV}
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
    - backendurbis

  api:
    container_name: container_api
    build: .
    image: 'node:lts-alpine'
    ports:
      - 3333:3333
    volumes:
      - .:/home/api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SQS_QUEUE_RECEIVE_EVENT=${AWS_SQS_QUEUE_RECEIVE_EVENT}
      - AWS_SQS_QUEUE_RECEIVE_MESSAGE_BODY=${AWS_SQS_QUEUE_RECEIVE_MESSAGE_BODY}
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - backendurbis

networks:
  backendurbis:
    driver: bridge
    
volumes:
  postgres_data:
